-- JaxGkv - Sistem Top Up QRIS
-- Jalankan seluruh file ini di Supabase SQL Editor.

-- =========================================================
-- 1) TABEL TOP UP
-- =========================================================

create table if not exists public.topup_request (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nominal bigint not null check (nominal > 0),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  proof_path text,
  rejection_reason text,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.topup_request add column if not exists proof_path text;
alter table public.topup_request add column if not exists rejection_reason text;
alter table public.topup_request add column if not exists reviewed_by uuid references auth.users(id);
alter table public.topup_request add column if not exists reviewed_at timestamptz;

-- Jika tabel lama belum memakai constraint status, validasi di bawah.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'topup_request_status_check'
      and conrelid = 'public.topup_request'::regclass
  ) then
    alter table public.topup_request
      add constraint topup_request_status_check
      check (status in ('pending','approved','rejected'));
  end if;
end $$;

create index if not exists topup_request_user_created_idx
  on public.topup_request(user_id, created_at desc);
create index if not exists topup_request_status_created_idx
  on public.topup_request(status, created_at desc);

-- =========================================================
-- 2) HELPER ADMIN
-- =========================================================

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- =========================================================
-- 3) RLS TOP UP
-- =========================================================

alter table public.topup_request enable row level security;

drop policy if exists "topup user select own" on public.topup_request;
drop policy if exists "topup user insert own" on public.topup_request;
drop policy if exists "topup admin select all" on public.topup_request;

create policy "topup user select own"
on public.topup_request
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "topup user insert own"
on public.topup_request
for insert
to authenticated
with check (
  user_id = auth.uid()
  and status = 'pending'
);

-- Tidak ada UPDATE/DELETE dari browser.
-- Perubahan status + saldo dilakukan lewat RPC SECURITY DEFINER.

-- =========================================================
-- 4) STORAGE BUCKET BUKTI PEMBAYARAN
-- =========================================================

insert into storage.buckets (id, name, public)
values ('topup-bukti', 'topup-bukti', false)
on conflict (id) do update set public = false;

drop policy if exists "topup proof upload own folder" on storage.objects;
drop policy if exists "topup proof read own or admin" on storage.objects;

create policy "topup proof upload own folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'topup-bukti'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "topup proof read own or admin"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'topup-bukti'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
  )
);

-- =========================================================
-- 5) APPROVE: ATOMIC + ANTI DOUBLE CREDIT
-- =========================================================

create or replace function public.approve_topup(request_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.topup_request%rowtype;
  admin_id uuid := auth.uid();
begin
  if not public.is_admin() then
    raise exception 'Akses ditolak: admin only';
  end if;

  select * into req
  from public.topup_request
  where id = request_id
  for update;

  if not found then
    raise exception 'Request top up tidak ditemukan';
  end if;

  if req.status <> 'pending' then
    raise exception 'Request sudah diproses dengan status %', req.status;
  end if;

  update public.profiles
  set saldo = coalesce(saldo, 0) + req.nominal
  where id = req.user_id;

  if not found then
    raise exception 'Profil user tidak ditemukan';
  end if;

  update public.topup_request
  set status = 'approved',
      reviewed_by = admin_id,
      reviewed_at = now(),
      rejection_reason = null
  where id = request_id;
end;
$$;

revoke all on function public.approve_topup(bigint) from public;
grant execute on function public.approve_topup(bigint) to authenticated;

-- =========================================================
-- 6) REJECT
-- =========================================================

create or replace function public.reject_topup(request_id bigint, reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.topup_request%rowtype;
  admin_id uuid := auth.uid();
  clean_reason text := nullif(trim(reason), '');
begin
  if not public.is_admin() then
    raise exception 'Akses ditolak: admin only';
  end if;

  if clean_reason is null then
    raise exception 'Alasan penolakan wajib diisi';
  end if;

  select * into req
  from public.topup_request
  where id = request_id
  for update;

  if not found then
    raise exception 'Request top up tidak ditemukan';
  end if;

  if req.status <> 'pending' then
    raise exception 'Request sudah diproses dengan status %', req.status;
  end if;

  update public.topup_request
  set status = 'rejected',
      rejection_reason = clean_reason,
      reviewed_by = admin_id,
      reviewed_at = now()
  where id = request_id;
end;
$$;

revoke all on function public.reject_topup(bigint, text) from public;
grant execute on function public.reject_topup(bigint, text) to authenticated;

-- =========================================================
-- 7) PERMISSION
-- =========================================================

grant select, insert on public.topup_request to authenticated;
